[project]
name = "nclusionpy"
version = "0.0.1"
description = ""

license = {text = "GPL-3.0 license"}
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "juliacall (>=0.9.28,<0.10.0)",
    "juliapkg (>=0.1.21,<0.2.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "numpy (>=2.3.3,<3.0.0)",
    "scanpy (>=1.11.4,<2.0.0)",
    "anndata (>=0.12.2,<0.13.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
